#pragma once
#define VERTICES_TRIANGLE \
{\
	Vertex{ Vector4(0.5, -0.8, 0.5) }, Vertex{ Vector4(-0.5, 0.8, 0.5)}, Vertex{ Vector4(-0.5, -0.8, 0.5)}, \
}

#define WORLD_UNIT 100
#define VERTICE_RIGHT_TOP_BACK Vertex { Vector4{0.5*WORLD_UNIT, 0.5*WORLD_UNIT, -0.5*WORLD_UNIT, 1}, {1,0,0, 1}, {1, 0}}
#define VERTICE_RIGHT_TOP_FRONT Vertex { Vector4{0.5*WORLD_UNIT, 0.5*WORLD_UNIT, 0.5*WORLD_UNIT, 1}, {0,1,0, 1}, {0, 0} }
#define VERTICE_LEFT_TOP_FRONT Vertex { Vector4{-0.5*WORLD_UNIT, 0.5*WORLD_UNIT, 0.5*WORLD_UNIT, 1}, {0,0,1, 1}, {1, 0} }
#define VERTICE_LEFT_TOP_BACK Vertex { Vector4{-0.5*WORLD_UNIT, 0.5*WORLD_UNIT, -0.5*WORLD_UNIT, 1}, {1,1,0, 1}, {0, 0} }
#define VERTICE_RIGHT_BOTTOM_BACK Vertex {Vector4{0.5*WORLD_UNIT, -0.5*WORLD_UNIT, -0.5*WORLD_UNIT, 1}, {1,0,1, 1}, {1, 1} }
#define VERTICE_RIGHT_BOTTOM_FRONT Vertex {Vector4{0.5*WORLD_UNIT, -0.5*WORLD_UNIT, 0.5*WORLD_UNIT, 1}, {0,1,1, 1}, {0, 1} }
#define VERTICE_LEFT_BOTTOM_FRONT Vertex {Vector4{-0.5*WORLD_UNIT, -0.5*WORLD_UNIT, 0.5*WORLD_UNIT, 1}, {0,0,0, 1}, {1, 1} }
#define VERTICE_LEFT_BOTTOM_BACK Vertex {Vector4{-0.5*WORLD_UNIT, -0.5*WORLD_UNIT, -0.5*WORLD_UNIT, 1}, {1,1,1, 1}, {0, 1} }

// order: top-bottom-right-left-front-back
#define VERTICES_CUBE \
{\
	VERTICE_RIGHT_TOP_BACK, VERTICE_RIGHT_TOP_FRONT, VERTICE_LEFT_TOP_FRONT, \
	VERTICE_RIGHT_TOP_BACK, VERTICE_LEFT_TOP_FRONT, VERTICE_LEFT_TOP_BACK, \
\
	VERTICE_LEFT_BOTTOM_BACK, VERTICE_LEFT_BOTTOM_FRONT, VERTICE_RIGHT_BOTTOM_FRONT, \
	VERTICE_LEFT_BOTTOM_BACK, VERTICE_RIGHT_BOTTOM_FRONT, VERTICE_RIGHT_BOTTOM_BACK, \
\
	VERTICE_RIGHT_BOTTOM_FRONT, VERTICE_RIGHT_TOP_FRONT, VERTICE_RIGHT_TOP_BACK, \
	VERTICE_RIGHT_BOTTOM_FRONT, VERTICE_RIGHT_TOP_BACK, VERTICE_RIGHT_BOTTOM_BACK, \
\
	VERTICE_LEFT_BOTTOM_BACK, VERTICE_LEFT_TOP_BACK, VERTICE_LEFT_TOP_FRONT, \
	VERTICE_LEFT_BOTTOM_BACK, VERTICE_LEFT_TOP_FRONT, VERTICE_LEFT_BOTTOM_FRONT, \
\
	VERTICE_LEFT_BOTTOM_FRONT, VERTICE_LEFT_TOP_FRONT, VERTICE_RIGHT_TOP_FRONT, \
	VERTICE_LEFT_BOTTOM_FRONT, VERTICE_RIGHT_TOP_FRONT, VERTICE_RIGHT_BOTTOM_FRONT, \
\
	VERTICE_RIGHT_BOTTOM_BACK, VERTICE_RIGHT_TOP_BACK, VERTICE_LEFT_TOP_BACK, \
	VERTICE_RIGHT_BOTTOM_BACK, VERTICE_LEFT_TOP_BACK, VERTICE_LEFT_BOTTOM_BACK, \
}

#define VERTICES_CUBE_TEST \
{\
	VERTICE_LEFT_TOP_BACK, VERTICE_LEFT_TOP_BACK, VERTICE_LEFT_TOP_FRONT, \
	VERTICE_LEFT_BOTTOM_BACK, VERTICE_LEFT_TOP_FRONT, VERTICE_LEFT_BOTTOM_FRONT, \
}

#define VERTICES_QUAD \
{\
	VERTICE_LEFT_TOP_BACK, VERTICE_LEFT_BOTTOM_BACK, VERTICE_RIGHT_BOTTOM_BACK, \
	VERTICE_RIGHT_TOP_BACK, VERTICE_LEFT_TOP_BACK, VERTICE_RIGHT_BOTTOM_BACK, \
}